export const selectRestaurantServices: { value: string; label: string }[] = [
    { label: 'Dine-In', value: 'Dine-In' },
    { label: 'Takeout', value: 'Takeout' },
    { label: 'Delivery', value: 'Delivery' },
    { label: 'Catering', value: 'Catering' },
    { label: 'Buffet', value: 'Buffet' },
    { label: 'Food Truck', value: 'Food Truck' },
    { label: 'Event Hosting', value: 'Event Hosting' },
    { label: 'Private Dining', value: 'Private Dining' },
    { label: 'Outdoor Seating', value: 'Outdoor Seating' },
    { label: 'Live Music', value: 'Live Music' },
    { label: 'Bar Services', value: 'Bar Services' },
    { label: 'Parking', value: 'Parking' },
    { label: 'Wi-Fi', value: 'Wi-Fi' },
    { label: 'Reservation', value: 'Reservation' },
    { label: 'Vegan Options', value: 'Vegan Options' },
    { label: 'Gluten-Free Options', value: 'Gluten-Free Options' },
    { label: 'Pet-Friendly', value: 'Pet-Friendly' },
    { label: 'Wheelchair Accessible', value: 'Wheelchair Accessible' },
    { label: 'Home Delivery', value: 'Home Delivery' },
    { label: 'Self-Service', value: 'Self-Service' },
    { label: 'Family-Friendly', value: 'Family-Friendly' },
    { label: 'Barbecue', value: 'Barbecue' },
    { label: 'Special Diet', value: 'Special Diet' },
    { label: 'Cooking Classes', value: 'Cooking Classes' },
    { label: 'Live Cooking', value: 'Live Cooking' },
    { label: 'Takeaway Counter', value: 'Takeaway Counter' },
    { label: 'Seasonal Menu', value: 'Seasonal Menu' },
    { label: 'Late Night Service', value: 'Late Night Service' },
    { label: 'All-You-Can-Eat', value: 'All-You-Can-Eat' },
    { label: 'Brunch', value: 'Brunch' },
    { label: 'Breakfast', value: 'Breakfast' },
    { label: 'Lunch', value: 'Lunch' },
    { label: 'Dinner', value: 'Dinner' },
    { label: 'Special Occasions', value: 'Special Occasions' },
    { label: 'Halaal', value: 'Halaal' },
    { label: 'Kosher', value: 'Kosher' },
    { label: 'International', value: 'International' }
  ];
  