export const selectCuisines: { value: string; label: string }[] = [
  { label: 'Africano', value: 'Africano' },
  { label: 'Americano', value: 'Americano' },
  { label: 'Andaluz', value: 'Andaluz' },
  { label: 'Arabic', value: 'Arabic' },
  { label: 'Argentino', value: 'Argentino' },
  { label: 'Arrocería', value: 'Arrocería' },
  { label: 'Asador', value: 'Asador' },
  { label: 'Asiático', value: 'Asiático' },
  { label: 'Catalán', value: 'Catalán' },
  { label: 'Chileno', value: 'Chileno' },
  { label: 'Chino', value: 'Chino' },
  { label: 'Cocina casera', value: 'Cocina casera' },
  { label: 'Creativo', value: 'Creativo' },
  { label: 'De Fusión', value: 'De Fusión' },
  { label: 'De mercado', value: 'De mercado' },
  { label: 'Ecuatoriano', value: 'Ecuatoriano' },
  { label: 'Español', value: 'Español' },
  { label: 'Europa de este', value: 'Europa de este' },
  { label: 'European', value: 'European' },
  { label: 'Francesa', value: 'Francesa' },
  { label: 'Gallego', value: 'Gallego' },
  { label: 'Gastronómico', value: 'Gastronómico' },
  { label: 'Hamburguesería', value: 'Hamburguesería' },
  { label: 'Indio', value: 'indio' },
  { label: 'Indonesio', value: 'Indonesio' },
  { label: 'Internacional', value: 'Internacional' },
  { label: 'Japonés', value: 'Japonés' },
  { label: 'Latino', value: 'Latino' },
  { label: 'Libanés', value: 'Libanés' },
  { label: 'Madrileño', value: 'Madrileño' },
  { label: 'Marisquería', value: 'Marisquería' },
  { label: 'Marroquí', value: 'Marroquí' },
  { label: 'Mediterráneo', value: 'Mediterráneo' },
  { label: 'Mexicano', value: 'Mexicano' },
  { label: 'Napolitano', value: 'Napolitano' },
  { label: 'Nepalíes', value: 'Nepalíes' },
  { label: 'Peruano', value: 'Peruano' },
  { label: 'Pizzeria', value: 'Pizzeria' },
  { label: 'Pub', value: 'Pub' },
  { label: 'Pulperia', value: 'Pulperia' },
  { label: 'Restaurante y tapatía', value: 'Restaurante y tapatía' },
  { label: 'Tailandés', value: 'Tailandés' },
  { label: 'Taparía', value: 'Taparía' },
  { label: 'Turquía', value: 'Turquía' },
  { label: 'Vasco', value: 'Vasco' },
  { label: 'Vegetariano', value: 'Vegetariano' },
  { label: 'Venezolano', value: 'Venezolano' },
  { label: 'francés', value: 'francés' },
  { label: 'italianos', value: 'italianos' }
];
