export enum tagTypes {
    userLoginInfo = "userLoginInfo",
    ownerInfo = "ownerInfo",
    holiday = "holiday",
    timeSlots = "timeSlots",
    CreateHoliday = "CreateHoliday",
    reviews = "reviews",
    replyReviews = "replyReviews",
    reviewDetails = "reviewDetails",
    menu = "menu",
    menuChild = "menuChild",
    menuList = "menuList",
    specialMenu = "specialMenu",
    discountMenu = "discountMenu",
    buffetMenu = "buffetMenu",
    menuCetegory = "menuCetegory",
    SingleMenuChild = "SingleMenuChild",
    UpdateSingleMenuChild = "UpdateSingleMenuChild",
    alert = "alert",
    image = "image",
    createRestaurant = "createRestaurant",
    singleCategory = "singleCategory",
    uploadProfileImage="uploadProfileImage",
    updateSpecialMenu="updateSpecialMenu",
    deleteSpecialMenu="deleteSpecialMenu",
}

export const tagTypesList = [
    tagTypes.userLoginInfo,
    tagTypes.ownerInfo,
    tagTypes.holiday,
    tagTypes.timeSlots,
    tagTypes.CreateHoliday,
    tagTypes.reviews,
    tagTypes.replyReviews,
    tagTypes.reviewDetails,
    tagTypes.buffetMenu,
    tagTypes.discountMenu,
    tagTypes.specialMenu,
    tagTypes.menu,
    tagTypes.menuChild,
    tagTypes.menuList,
    tagTypes.menuCetegory,
    tagTypes.SingleMenuChild,
    tagTypes.UpdateSingleMenuChild,
    tagTypes.alert,
    tagTypes.image,
    tagTypes.createRestaurant,
    tagTypes.singleCategory,
    tagTypes.uploadProfileImage,
    tagTypes.updateSpecialMenu,
    tagTypes.deleteSpecialMenu,
];
