export enum tagTypes {
<<<<<<< HEAD
  userLoginInfo = "userLoginInfo",
  registration = "registration",
  ownerInfo = "ownerInfo",
  holiday = "holiday",
  timeSlots = "timeSlots",
  CreateHoliday = "CreateHoliday",
  reviews = "reviews",
  replyReviews = "replyReviews",
  reviewDetails = "reviewDetails",
  country = "country",
  createRestaurant = "createRestaurant",
  uploadProfileImage = "uploadProfileImage",
  image = "image",
}

export const tagTypesList = [
  tagTypes.userLoginInfo,
  tagTypes.ownerInfo,
  tagTypes.holiday,
  tagTypes.timeSlots,
  tagTypes.CreateHoliday,
  tagTypes.reviews,
  tagTypes.replyReviews,
  tagTypes.reviewDetails,
  tagTypes.registration,
  tagTypes.country,
  tagTypes.createRestaurant,
  tagTypes.uploadProfileImage,
  tagTypes.image,
=======
    userLoginInfo = "userLoginInfo",
    ownerInfo = "ownerInfo",
    holiday = "holiday",
    timeSlots = "timeSlots",
    CreateHoliday = "CreateHoliday",
    reviews = "reviews",
    replyReviews = "replyReviews",
    reviewDetails = "reviewDetails",
    menu = "menu",
    specialMenu = "specialMenu",
    discountMenu = "discountMenu",
    buffetMenu = "buffetMenu",
}

export const tagTypesList = [
    tagTypes.userLoginInfo,
    tagTypes.ownerInfo,
    tagTypes.holiday,
    tagTypes.timeSlots,
    tagTypes.CreateHoliday,
    tagTypes.reviews,
    tagTypes.replyReviews,
    tagTypes.reviewDetails,
    tagTypes.buffetMenu,
    tagTypes.discountMenu,
    tagTypes.specialMenu,
    tagTypes.menu,
>>>>>>> c37f9af2dc1fc0ce18139f7bb14f82f129528773
];
